[theme]
# Primary accent color for interactive elements.
primaryColor = "#004D40"

# Background color for the main content area.
backgroundColor = "#900C3F"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#581845"

# Color used for almost all text.
textColor = "#ffffff"
